#|
Section 2.3.3
This file contains the procedures for the section 2.3.3 of the book
|#

(define (element-of-set? x S)
    (cond ((null? S) #f)
        ((= x (car S)) #t)
        (else (element-of-set? x (cdr S)))
    )
)

(define (adjoin-set x S)
    (if (element-of-set? x S)
        S
        (cons x S)
    )
)

(define (intersection-set S1 S2)
    (cond ((or (null? S1) (null? S2)) '())
    ((element-of-set? (car S1) S2) (cons (car S1) (intersection-set (cdr S1) S2)))
    (else (intersection-set (cdr S1) S2))
))


(define (union-set S1 S2)
    (cond ((null? S2) S1)
        ((element-of-set? (car S2) S1) (union-set S1 (cdr S2)))
        (else (union-set (adjoin-set (car S2) (cdr S2))))
    )
)

(define (element-of-set-duplicate? x S)
    ; O(n)
    (cond ((null? S) #f)
        ((= x (car S)) #t)
        (else (element-of-set? x (cdr S)))
    )
)

(define (adjoin-set-duplicate x S)
    ; O(1)
    (cons x S)
)

(define (intersection-set-duplicate S1 S2)
    (append S1 S2)
)

(define (element-of-set-ordered? x S)
    (cond ((null? S) #f)
        ((> x (car S)) #f)
        ((= x (car S)) #t)
        (else (element-of-set-ordered x (cdr S)))
    )
)

(define (intersection-set-ordered S1 S2)
    (cond ((or (null? S1) (null? S2)) '())
        ((= (car S1) (car S2)) (cons (car S1) intersection-set-ordered (cdr S1) (cdr S2)))
        ((> (car S1) (car S2)) (intersection-set-ordered S1 (cdr S2)))
        (else (intersection-set-ordered (cdr S1) S2))
)

(define (adjoin-set-ordered x S)
    (cond ((null? S) x)
        ((= x (car S)) S)
        ((> x (car S)) (cons x S))
        (else (cons (car S) (adjoin-set-ordered x (cdr S))))
    )
)

(define (union-set-ordered S1 S2)
    (cond ((null? S2) S1)
        ((= (car S1) (car S2)) (cons (car S1) (union-set-ordered S1 S2)))
        ((> (car S1) (car S2)) (cons (car S2) (union-set-ordered S1 (cdr S2))))
        (else (cons (car S1) (union-set-ordered (cdr S1) S2)))
    )
)

(define (entry tree)
    (car tree)
)

(define (left-branch tree)
    (cadr tree)
)

(define (right-branch tree)
    (caddr tree)
)

(define (make-tree entry left-branch right-branch)
    (list entry left-branch right-branch)
)

(define (element-of-tree-set? x set)
    (cond ((null? set) #f)
        ((= x (entry set)) #t)
        ((> x (entry set)) (element-of-tree-set? x (right-branch set)))
        (else (element-of-tree-set? x (left-branch set)))
    )
)

(define (adjoin-tree-set x set)
    (cond ((null? set) x) 
        ((= x (entry set)) set)
        ((> x (entry set)) (list (entry set) (left-branch set) (adjoin-tree-set x (right-branch set))))
        (else (list (entry set) (adjoin-tee-set x (left-branch set)) (right-branch set)))
    )
)

(define (tree->list-1 tree)
    (if (null? tree) 
        '()
        (append (tree->list-1 (left-branch tree)) 
            (cons (entry tree) (tree->list-1 (right-branch tree)))
        )
    )
)

(define (tree->list-2 tree)
    (define (copy-to-list tree result-list)
        (if (null? tree) 
            result-list
            (copy-to-list 
                (left-branch tree)
                (cons (entry tree) (copy-to-list (right-branch tree) result-list))
            )
        )
    )
)

(define (list->tree elements)
    (car (partial-tree elements (length elements)))
)

(define (partial-tree elts n)
    (if (= n 0)
        (cons '() elts)
        (let ((left-size (quotient (- n 1) 2)))
            (let ((left-result (partial-tree elts left-size)))
                (let ((left-tree (car left-result))
                      (non-left-elts (cdr left-result))
                      (right-size (- n (+ left-size 1))))
                    (let ((this-entry (car non-left-elts))
                          (right-result (partial-tree (cdr non-left-elts) right-size)) 
                        )
                        (let ((right-tree (car right-result))
                              (remaining-elts (cdr right-result))
                            )
                            (cons (make-tree this-entry left-tree right-tree) (remaining-elts))
                        )
                    )
                )
            )
        )
    )
)


(define (union-balanced-tree-set S1 S2)
    (list->tree (union-set-ordered (tree->list-2 S1) (tree->list-2 S2)))
)

(define (lookup given-key records)
    (cond ((null? records) #f)
        ((equal? given-key (key (car records))) (car records))
        (else (lookup given-key (cdr records)))
    )
)

(define (lookup-tree given-key records)
    (cond ((null? records) #f) 
        ((= given-key (key (entry records))) (entry records))
        ((> given-key (key (entry records))) (lookup-tree given-key (right-branch records)))
        (else (lookup-tree given-key (left-branch records)))
    )
)